[[redirects]]
  from = "/countries"
  to = "/data/countries.geo.json"
  status = 200

[[redirects]]
  from = "/countries/USA/*"
  to = "/data/countries/:state"
  status = 200

[[redirects]]
  from = "/countries/USA/*"
  to = "/data/countries/:state"
  status = 200

[[redirects]]
  from = "/countries/CAN/*"
  to = "/data/countries/:province"
  status = 200